### ISSUE TITLE
mobiler

### ISSUE THREAD

**Issue by theeal** [Lantmateriet/Example-consuming-WMTS#1]
Jag upplever att det är svårt att visa kartan på mobilen ibland. Ex på min z5 fungerar det i Firefox men inte i Chrome. På en nexus 9 platta, funkar det inte alls. 
Vilken version av Open layer används? 
Kan man få hjälp att lägga in kml?

**Comment by bkalzen** [comment]
Vi använder Openlayers 3.

Det här exemplet är bara tänkt för att visa hur man kan hämta kartdata från våra öppna data, så vi har inget exempel på hur man lägger till kml-objekt.

Om du har problem med vissa enheter så kan du testa att köra "Öppna data"-sidan som använder samma kod:
[https://kso.etjanster.lantmateriet.se/oppnadata.html](url)

Om du får fel även där så går det bra att lämna ett detaljerat felmeddelande på:
[http://www.lantmateriet.se/synpunkter-kso](url)

**Comment by theeal** [comment]
Det verkar som om koden på https://kso.etjanster.lantmateriet.se/oppnadata.html fungerar bättre.
