### ISSUE TITLE
Coordinates does not match.

### ISSUE THREAD

**Issue by carlrosell** [Lantmateriet/Example-consuming-WMTS#2]
Just by adding the standard OSM map you can clearly see that the map isn't aligned at all. 

![screen shot 2016-08-25 at 09 28 05](https://cloud.githubusercontent.com/assets/2036823/17960644/974bc83c-6aa7-11e6-8ae3-d7fe17319d5e.png)

**Comment by ptomgab** [comment]
Notice that the original map is in the referense system SWEREF 99 TM (EPSG code 3006)
Check doc at  https://www.lantmateriet.se/en/Maps-and-geographic-information/Geodata-services/Visningstjanster/topografisk-webbkarta-visning-cc-by/

**Comment by carlrosell** [comment]
Oh I see. Adding the code for mapping them together might be good though :+1:
