### ISSUE TITLE
saknar kredit till openlayers

### ISSUE THREAD

**Issue by nicklasaven** [Lantmateriet/Example-consuming-WMTS#4]
Det är väldigt kul att lantmäteriet börjar ta till sig open source-programvara.

Jag tycker det kunde framkomma lite tydligare att det är openlayers som ligger bakom det hela.

Det tror jag uppskattas av de som lagt tiotusentals timmar på projektet.

Ser fram emot fortsättningen på Lantmäteriets open source-äventyr och öppna data :-)

MVH

Nicklas

**Comment by magnusheino** [comment]
Nu finns openlayers i readme och beskrivning.
